safe: true
lsi: false
markdown: rdiscount
pygments: true
default_locale: "de"
redirects: yes

locales:
  en:
    header: 
      navigation:
        start:
          text: "Schwerathlet"
          file: index
        location:
          text: "Location"
          file: location
        knowledge:
          text: "Knowledge Base"
          file: knowledge-base
        about:
          text: "About"
          file: about
        contact:
          text: "Contact"
          file: contact
    footer:
      language:
        text: "Language"
        locales:
          - text: "German"
            locale: de
          - text: "English"
            locale: en
    start:
      header: "Schwerathlet"
      message: "Train your endurance, stamina, strength, flexibility, power, coordination, agility, balance and accuracy."
  de:
    header:
      navigation:
        start:
          text: "Schwerathlet"
          file: index
        location:
          text: "Standort"
          file: standort
        knowledge:
          text: "Grundlagenwissen"
          file: grundlagenwissen
        about:
          text: "Impressum"
          file: impressum
        contact:
          text: "Kontakt"
          file: kontakt 
    footer:
      language:
        text: "Sprache"
        locales:
          - locale: de
            text: "Deutsch"
          - locale: en
            text: "Englisch"
    start:
      header: "Schwerathlet"
      message: "Trainiere deine Ausdauer, Kraft, Beweglichkeit, Schnelligkeit, Geschicklichkeit, Balance, Koordination und Genauigkeit." 
