safe: true
lsi: false
markdown: rdiscount
pygments: true
default_locale: "de"
redirects: yes

locales:
  en:
    nav:
    - text: "Schwerathlet"
      url: /en/index.html
      layout: heading
    - text: "Location"
      url: /en/location.html
    - text: "Knowledge Base"
      url: /en/knowledge-base.hmtl
    - text: "About"
      url: /en/about.html
    - text: "Contact"
      url: /en/contanct.html
    welcome_message: "Train your endurance, stamina, strength, flexibility, power, coordination, agility, balance and accuracy."
  de:
    nav:
    - text: "Schwerathlet"
      url: /de/index.html
      layout: heading
    - text: "Standort"
      url: /de/standort.html
    - text: "Grundlagenwissen"
      url: /de/grundlagenwissen.html
      layout: post
    - text: "Impressum"
      url: /de/impressum.html
    - text: "Kontakt"
      url: /de/kontakt.html
    welcome_message: "Trainiere deine Ausdauer, Kraft, Beweglichkeit, Schnelligkeit, Geschicklichkeit, Balance, Koordination und Genauigkeit." 
